version: "3.8"

volumes:
  go-modules:

services:
  database:
    container_name: database
    image: postgres:14.2
    restart: on-failure
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
    volumes:
      - "./db-init.sql:/docker-entrypoint-initdb.d/init.sql"
